server:
  port: 8080

spring:
  application:
    name: spamer-monolith
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/spamer}
    username: ${DB_USERNAME:spamer}
    password: ${DB_PASSWORD:spamer}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health
